# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-byte-order-marker  # Forbid UTF-8 byte-order markers
        name: CMS User Authentication hooks....Check for byte-order-marker
      # Check for files with names that would conflict on a case-insensitive
      # filesystem like MacOS HFS+ or Windows FAT.
      - id: check-case-conflict
        name: CMS User Authentication hooks....Check for case conflicts
      - id: check-json
        name: CMS User Authentication hooks....Check JSON
      - id: check-yaml
        name: CMS User Authentication hooks....Check Yaml
        exclude: (^.*/catalog-info.yaml)
      - id: check-toml
        name: CMS User Authentication hooks....Check Toml
      - id: check-merge-conflict
        name: CMS User Authentication hooks....Check for merge conflicts
      - id: check-added-large-files
        name: CMS User Authentication hooks....Check for added large files
        exclude: |
          (?x)^(
            ^.*/package-lock.json |
            ^.*/yarn.lock |
            ^.*/Pipfile.lock
          )$
      - id: end-of-file-fixer
        name: CMS User Authentication hooks....Fix End of Files
      - id: fix-encoding-pragma
        name: CMS User Authentication hooks....Fix python encoding pragma
      - id: trailing-whitespace
        name: CMS User Authentication hooks....Trim Trailing Whitespace
      - id: mixed-line-ending
        name: CMS User Authentication hooks....Mixed line ending
      - id: sort-simple-yaml # Requires explicit files parameter to enable file matching
        name: CMS User Authentication hooks....Sort simple YAML files
      - id: detect-aws-credentials
        name: CMS User Authentication hooks....Detect AWS Credentials
        args: ["--credentials-file", "~/.ada/credentials"]
      - id: detect-private-key
        name: CMS User Authentication hooks....Detect Private Key
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        name: CMS User Authentication hooks....Insert license in comments
        files: \.py$
        args:
          - --license-filepath
          - ./license_header.txt        # defaults to: LICENSE.txt
          - --detect-license-in-X-top-lines=3

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: CMS User Authentication hooks....black
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        name: CMS User Authentication hooks....pycln
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: CMS User Authentication hooks....isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: CMS User Authentication hooks....bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
  # - repo: https://github.com/kontrolilo/kontrolilo
  #   rev: v2.2.0
  #   hooks:
  #     - id: license-check-configuration-lint
  #       name: CMS User Authentication hooks....license-check-configuration-lint
  #     - id: license-check-pipenv
  #       name: CMS User Authentication hooks....license-check-pipenv
  #     - id: license-check-npm
  #       name: CMS User Authentication hooks....license-check-npm
  - repo: https://github.com/pypa/pip-audit
    rev: v2.6.1
    hooks:
      - id: pip-audit
        name: CMS User Authentication hooks....pip-audit

# Local hooks
  - repo: local
    hooks:
    - id: check-bash-syntax
      name: CMS User Authentication hooks....Check Shell scripts syntax correctness
      language: system
      entry: bash -n
      files: \.sh$
  - repo: local
    hooks:
      - id: cms-user-authentication-pylint
        name: CMS User Authentication hooks....pylint
        entry: pylint
        args: ["--extension-pkg-allow-list", "math"]
        types: [python]
        language: system
  - repo: local
    hooks:
      - id: cms-user-authentication-mypy
        name: CMS User Authentication hooks....mypy
        entry: mypy
        types_or: [python, pyi]
        args: ["--strict", "--cache-dir", "/dev/null"]
        language: system
  - repo: local
    hooks:
      - id: cms-authentication-cfn-nag
        name: CMS User Authentication hooks....cfn-nag
        entry: templates/modules/cms_user_authentication_on_aws/v1/instance_infrastructure/deployment/run-cfn-nag.sh
        files: infrastructure
        language: system
        types_or: [python, json]
        pass_filenames: false
  - repo: local
    hooks:
      - id: cms-user-authentication-pytest
        name: CMS User Authentication hooks....pytest
        entry: templates/modules/cms_user_authentication_on_aws/v1/instance_infrastructure/deployment/run-unit-tests.sh
        args: ["--no-report"]
        language: system
        types: [python]
        pass_filenames: false
