# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: name-tests-test
        name: (Backstage) Check test naming
        args: ["--pytest-test-first"]
        exclude: (tests/?.*/fixture(s)?_.*\.py$)
      - id: check-executables-have-shebangs
        name: (Backstage) Check executables have shebangs
      - id: fix-byte-order-marker
        name: (Backstage) Fix byte order marker
      - id: check-case-conflict
        name: (Backstage) Check case conflict
      - id: check-json
        name: (Backstage) Check json
      - id: check-yaml
        name: (Backstage) Check yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: check-toml
        name: (Backstage) Check toml
      - id: check-merge-conflict
        name: (Backstage) Check for merge conflicts
      - id: check-added-large-files
        name: (Backstage) Check for added large files
        exclude: |
          (?x)^(
            ^.*/package-lock.json |
            ^.*/yarn.lock |
            ^.*/Pipfile.lock
          )$
      - id: end-of-file-fixer
        name: (Backstage) Fix end of files
      - id: fix-encoding-pragma
        name: (Backstage) Fix python encoding pragma
      - id: trailing-whitespace
        name: (Backstage) Trim trailing whitespace
      - id: mixed-line-ending
        name: (Backstage) Mixed line ending
      - id: detect-aws-credentials
        name: (Backstage) Detect AWS credentials
        args: ["--credentials-file", "~/.ada/credentials"]
      - id: detect-private-key
        name: (Backstage) Detect private keys
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        name: (Backstage) Insert license header (python)
        files: \.py$
        args:
          - --license-filepath
          - ./license_header.txt
          - --detect-license-in-X-top-lines=3
      - id: insert-license
        name: (Backstage) Insert license header (typescript and javascript)
        files: \.tsx$|\.ts$|\.js$|\.jsx$
        args:
          - --license-filepath
          - ./license_header.txt
          - --comment-style
          - // # defaults to Python's # syntax, requires changing for typescript syntax.
          - --detect-license-in-X-top-lines=3
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: (Backstage) Black
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        name: (Backstage) Pycln
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: (Backstage) Isort (python)
        args: ["--skip-glob", "**/node_modules/* **/.venv/*", "--settings-path", "./source/modules/backstage/pyproject.toml"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: (Backstage) Bandit
        args: ["-c", "./source/modules/backstage/pyproject.toml"]
        additional_dependencies: [ "bandit[toml]" ]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.6.1
    hooks:
      - id: pip-audit
        name: (Backstage) Pip audit
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: (Backstage) Prettier
        types_or: [javascript, jsx, ts, tsx]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        name: (Backstage) MarkdownLint
  # Local
  - repo: local
    hooks:
      - id: shellcheck
        name: (Backstage) Shellchecker
        entry: shellcheck
        args: ["-x"]
        types: [shell]
        language: system
      - id: pylint
        name: (Backstage) pylint
        entry: pylint
        args: ["--extension-pkg-allow-list", "math", "--rcfile", "./source/modules/backstage/pyproject.toml"]
        types: [python]
        language: system
      - id: mypy
        name: (Backstage) mypy
        entry: mypy
        types_or: [python, pyi]
        args: ["--strict", "--cache-dir", "./source/modules/backstage/.mypy_cache", "--config-file", "./source/modules/backstage/pyproject.toml"]
        language: system
      - id: run-tsc-backstage
        name: (Backstage) Run tsc on Backstage
        entry: source/modules/backstage/deployment/run-backstage-lint.sh
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
