enableExperimentalRedirectFlow: ${USE_BACKSTAGE_AUTH_REDIRECT_FLOW}

app:
  title: ${BACKSTAGE_NAME}
  baseUrl: https://${WEB_HOSTNAME}

organization:
  name: ${BACKSTAGE_ORG}

acdp:
  s3Catalog:
    bucketName: ${LOCAL_ASSET_BUCKET_NAME}
    prefix: ${LOCAL_ASSET_BUCKET_CATALOG_KEY_PREFIX}
    region: ${LOCAL_ASSET_BUCKET_REGION}
  buildConfig:
    buildConfigStoreSsmPrefix: ${ACDP_BUILD_CONFIG_SSM_PREFIX}
  deploymentDefaults:
    codeBuildProjectArn: ${CODEBUILD_PROJECT_ARN}
    accountId: ${DEFAULT_TARGET_ACCOUNT_ID}
    region: ${DEFAULT_TARGET_REGION}
  accountDirectory:
    enableMultiAccountDeployment: ${ENABLE_MULTI_ACCOUNT_DEPLOYMENT}
    organizationsAccountId: ${ORGS_MANAGEMENT_AWS_ACCOUNT_ID}
    organizationsManagementAccountRegion: ${ORGS_MANAGEMENT_ACCOUNT_REGION}
    organizationsAccountAssumeRoleName: ${ORGS_ACCOUNT_DIRECTORY_ASSUME_ROLE_NAME}
    availableRegionsParameterName: ${ORGS_AVAILABLE_REGIONS_SSM_PARAMETER_NAME}
    enrolledOrgsParameterName: ${ORGS_ENROLLED_ORGS_SSM_PARAMETER_NAME}
    metricsRoleName: ${METRICS_ROLE_NAME}
  metrics:
    userAgentString: ${USER_AGENT_STRING}
  operationalMetrics:
    solutionVersion: ${SOLUTION_VERSION}
    solutionId: ${SOLUTION_ID}
    deploymentUuid: ${DEPLOYMENT_UUID}
    sendAnonymousMetrics: ${SEND_ANONYMOUS_METRICS}
backend:
  auth: # Legacy auth is required for supporting certain plugins: https://backstage.io/docs/auth/service-to-service-auth/#legacy-tokens
    externalAccess:
      - type: legacy
        options:
          secret: ${BACKEND_SECRET}
          subject: legacy-auth-option
  baseUrl: https://${BACKEND_HOSTNAME}
  listen:
    port: 8080
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin:
      - https://${WEB_HOSTNAME}:443
      - https://${WEB_HOSTNAME}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  cache:
    store: memory

techdocs:
  generator:
    runIn: 'local'
  builder: 'local'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${LOCAL_ASSET_BUCKET_NAME}
      region: ${LOCAL_ASSET_BUCKET_REGION}
      bucketRootPath: ${LOCAL_ASSET_BUCKET_TECHDOCS_KEY_PREFIX}

permission:
  enabled: true
  rbac:
    policies-csv-file: ./default_permission_policies.csv # This file is copied to the container root in the Dockerfile
    policyFileReload: true
    admin:
      superUsers:
        - name: user:acdp/${ADMIN_USERNAME}
    pluginsWithPermission:
      - catalog
      - scaffolder
      - permission
      - acdp

auth:
  environment: production
  session: # Session secret is necessary to enable session support in the auth-backend
    secret: ${BACKEND_SECRET}
  providers:
    oauth2:
      production:
        clientId: ${CLIENT_ID}
        clientSecret: ${CLIENT_SECRET}
        authorizationUrl: ${AUTHORIZATION_URL}
        tokenUrl: ${TOKEN_URL}
  config:
    additionalScopes: ${BACKSTAGE_ADDITIONAL_SCOPES}

scaffolder:
  concurrentTasksLimit: 10

catalog:
  providers:
    awsS3:
      localAssetBucketEntities:
        bucketName: ${LOCAL_ASSET_BUCKET_NAME}
        prefix: ${LOCAL_ASSET_BUCKET_ENTITIES_PREFIX}
        region: ${LOCAL_ASSET_BUCKET_REGION}
        schedule:
          frequency:
            minutes: ${LOCAL_ASSET_BUCKET_DISCOVERY_REFRESH_FREQ}
          timeout: { minutes: 3 }
      localAssetBucketDefaultEntities:
        bucketName: ${LOCAL_ASSET_BUCKET_NAME}
        prefix: ${LOCAL_ASSET_BUCKET_DEFAULT_ENTITIES_PREFIX}
        region: ${LOCAL_ASSET_BUCKET_REGION}
        schedule:
          frequency:
            minutes: ${LOCAL_ASSET_BUCKET_DISCOVERY_REFRESH_FREQ}
          timeout: { minutes: 3 }
  locations:
    - type: url
      target: "https://github.com/aws-solutions/connected-mobility-solution-on-aws-public-assets/blob/release/v1/backstage-assets/all.yaml"
      rules:
        - allow: [Location, PartnerOffering]
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Template, PartnerOffering]
