# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

#This finch-compose deploys a postgres database that can be used for local testing in conjunction w/ app-config.local.yaml

version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - NODE_OPTIONS=--no-node-snapshot
    ports:
      - '5432:5432'
    container_name: "backstage-local-db"
