version: 0.2

phases:
  build:
    commands:
      - echo "Retrieving current account ID..."
      - CURRENT_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - if [ "$AWS_ACCOUNT_ID" = "$CURRENT_ACCOUNT_ID" ]; then
          export CLOUDFORMATION_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${DEFAULT_CLOUDFORMATION_ROLE_NAME}";
          echo "Target account ID matches the current account ID. Skipping role assumption.";
        else
          echo "Target account ID (${AWS_ACCOUNT_ID}) is different. Assuming role in the target account...";
          export ASSUME_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${DEPLOYMENT_ROLE_NAME}-${AWS_REGION}";
          export CLOUDFORMATION_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLOUDFORMATION_ROLE_NAME}-${AWS_REGION}";
          TEMP_CREDS=$(aws sts assume-role --role-arn "$ASSUME_ROLE_ARN" --role-session-name "CodeBuildSession" || echo "");
          export AWS_ACCESS_KEY_ID=$(echo "$TEMP_CREDS" | jq -r '.Credentials.AccessKeyId');
          export AWS_SECRET_ACCESS_KEY=$(echo "$TEMP_CREDS" | jq -r '.Credentials.SecretAccessKey');
          export AWS_SESSION_TOKEN=$(echo "$TEMP_CREDS" | jq -r '.Credentials.SessionToken');
        fi
      # Build and deploy
      - |
        aws cloudformation create-stack \
        --stack-name "${MODULE_STACK_NAME}" \
        --template-url "${CFN_TEMPLATE_URL}" \
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
        --role-arn "${CLOUDFORMATION_ROLE_ARN}" \
        --parameters \
        "[{\"ParameterKey\":\"IdentityProviderId\",\"ParameterValue\":\"${IDENTITY_PROVIDER_ID}\"}, \
          {\"ParameterKey\":\"ShouldCreateCognitoResources\",\"ParameterValue\":\"${SHOULD_CREATE_COGNITO_RESOURCES}\"}, \
          {\"ParameterKey\":\"CallbackUrls\",\"ParameterValue\":\"${CALLBACK_URLS}\"}, \
          {\"ParameterKey\":\"IdPConfigSecretArn\",\"ParameterValue\":\"${IDP_CONFIG_SECRET_ARN}\"}, \
          {\"ParameterKey\":\"ServiceClientConfigSecretArn\",\"ParameterValue\":\"${SERVICE_CLIENT_CONFIG_SECRET_ARN}\"}, \
          {\"ParameterKey\":\"UserClientConfigSecretArn\",\"ParameterValue\":\"${USER_CLIENT_CONFIG_SECRET_ARN}\"}]"
