schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "CMSEnvironment"
  types:
    CMSEnvironment:
      type: object
      description: "The primary environment for the Connected Mobility Solution on AWS"
      properties:
        a_number:
          title: "A number option"
          type: number
          description: "A number with a min and max"
          default: 80
          minimum: 0
          maximum: 65535
