AWSTemplateFormatVersion: '2010-09-09'
Description: The template creates Transit Gateway Routes between a public and private VPC
Parameters:
  RouteTableName:
    Type: String
  PrivateVpcCidr:
    Description: CIDR block of the private VPC to allow routing to/from the internet via the Transit Gateway
    Type: String
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid CIDR range in the form x.x.x.x/xx
  TransitGatewayId:
    Description: Id of the Transit Gateway
    Type: String
    AllowedPattern: "tgw-[0-9a-f]{8,17}"
    ConstraintDescription: "Must be a valid Transit Gateway ID (e.g., tgw-xxxxxxxxxxxxxxx)."
  PublicVpcTransitGatewayAttachmentId:
    Type: String
    Description: The Transit Gateway Attachment Id for the Public VPC
    AllowedPattern: "tgw-attach-[0-9a-f]{8,17}"
    ConstraintDescription: "Must be a valid VPC Transit Gateway Attachment ID (e.g., tgw-attach-xxxxxxxxxxxxxxx)."
  PrivateVpcTransitGatewayAttachmentId:
    Type: String
    Description: The Transit Gateway Attachment Id for the Private VPC
    AllowedPattern: "tgw-attach-[0-9a-f]{8,17}"
    ConstraintDescription: "Must be a valid VPC Transit Gateway Attachment ID (e.g., tgw-attach-xxxxxxxxxxxxxxx)."


Resources:

  TransitGatewayRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      Tags:
        - Key: Name
          Value: !Ref RouteTableName
      TransitGatewayId: !Ref TransitGatewayId

  PublicVpcTgwRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref PublicVpcTransitGatewayAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  PrivateVpcTgwRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref PrivateVpcTransitGatewayAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  PublicVpcTransitGatewayRoute:
    Type: "AWS::EC2::TransitGatewayRoute"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      TransitGatewayAttachmentId: !Ref PublicVpcTransitGatewayAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  PrivateVpcTransitGatewayRoute:
    Type: "AWS::EC2::TransitGatewayRoute"
    Properties:
      DestinationCidrBlock: !Ref PrivateVpcCidr
      TransitGatewayAttachmentId: !Ref PrivateVpcTransitGatewayAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable
