apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: A CDK Python app for authenticating CMS users and services
  name: cms-auth
  tags:
  - cms
  - auth
  - authorization-code
  - token-validation
  title: CMS Auth Module
  annotations:
    backstage.io/techdocs-ref: dir:../../docs/components/cms-auth/
spec:
  type: service
  output:
    links:
    - entityRef: ${{ steps.catalogRegister.output.entityRef }}
      icon: catalog
      title: Open in catalog
  owner: aws solutions
  parameters:
  - properties:
      componentId:
        default: cms-auth
        description: Unique name of the component
        pattern: '[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z]'
        title: Name
        type: string
        ui:field: EntityNamePicker
      description:
        default: A CDK Python app for authenticating CMS users and services
        description: Help others understand what this component is for.
        title: Description
        type: string
      owner:
        description: Owner of the component
        title: Owner
        type: string
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind:
            - Group
            - User
    required:
      - componentId
      - owner
    title: Provide the required information
  - properties:
      targetAwsAccountId:
        description: Target AWS Account ID to deploy the module
        pattern: '^\d{12}$'
        title: Target AWS Account Id
        type: string
        ui:field: AwsAccountId
      targetAwsRegion:
        description: Target AWS Region to deploy module
        pattern: '^(us|eu|ap|sa|ca|me|af|il)-(north|south|east|west|central)-(1|2|3|4)$'
        title: Target AWS Region
        type: string
        ui:field: AwsRegion
    required:
      - targetAwsAccountId
      - targetAwsRegion
    title: Provide the target account information
  - properties:
      appUniqueId:
        default: cms
        description: Application unique identifier used to uniquely name resources within the stack
        title: App Unique ID
        type: string
        ui:disabled: true
    required:
      - appUniqueId
    title: Provide the Module Configuration
  steps:
  - action: aws:acdp:catalog:create
    id: acdpCatalogCreate
    name: ACDP S3 Catalog Create
    input:
      componentId: ${{ parameters.componentId }}
      assetsSourcePath: dir:../../acdp/cms-auth/
      docsSiteSourcePath: dir:../../docs/components/cms-auth/site/
      entity:
        apiVersion: backstage.io/v1alpha1
        kind: Component
        metadata:
          annotations:
            aws.amazon.com/acdp-deploy-on-create: "true"
            aws.amazon.com/acdp-deployment-target-account: ${{parameters.targetAwsAccountId}}
            aws.amazon.com/acdp-deployment-target-region: ${{parameters.targetAwsRegion}}
          description: ${{parameters.description}}
          name: ${{parameters.componentId}}-${{parameters.targetAwsAccountId}}-${{parameters.targetAwsRegion}}
          namespace: acdp
        spec:
          lifecycle: experimental
          owner: ${{parameters.owner}}
          type: service

  - action: catalog:register
    id: catalogRegister
    name: Backstage Catalog Register
    input:
      catalogInfoUrl: ${{ steps.acdpCatalogCreate.output.catalogItemS3Url }}

  - action: aws:acdp:configure
    id: acdpConfigureDeploy
    name: ACDP Configure Deploy
    input:
      entityRef: ${{ steps.catalogRegister.output.entityRef }}
      buildParameters:
      - name: CFN_TEMPLATE_URL
        value: UNSET
      - name: APP_UNIQUE_ID
        value: ${{ parameters.appUniqueId }}
